### ISSUE TITLE
slouchstoppah.com domain expired?

### ISSUE THREAD

**Issue by carlin-q-scott** [lnenad/slouch-stoppah#3]
Hi, I tried loading the site today and got a security error stating the cert was for shafeehaque.com. After a couple of retries I'm now seeing a Godaddy page stating the domain registration has expired.

**Comment by Samir-Rashid** [comment]
I have the same issue. I'll host a mirror later today.

**Comment by lnenad** [comment]
Really sorry this happened @carlin-q-scott @Samir-Rashid . Tbh I didn't think anyone was using the site so I thought that after 4/5 years it was time to let it go. I've just redeployed it to https://slouchstoppuh.com, note the change from stoppah to stoppuh and I'll keep it live. I'm very happy to hear someone is still using it other than me :). I'll update the docs. Thank you guys!

**Comment by carlin-q-scott** [comment]
@lnenad I'd be happy to contribute $5 towards your domain registration costs if you set up your GitHub Sponsors account.

**Comment by lnenad** [comment]
@carlin-q-scott appreciate that very much but it is not needed. It wasn't about the money, it was more due to just having to think about it 🧠 .

**Comment by Samir-Rashid** [comment]
I have put up a mirror at https://slouch.godsped.com/ and https://samir-rashid.github.io/slouch-stoppah. These should stay up as long as I am alive.
I removed google tag tracking, automatic tracking stopped, and the intro modal.
